export const products = [
  {
    id: 1,
    title: "Fjallraven - Foldsack No. 1 Backpack, Fits 15 Laptops",
    price: 109.95,
    description:
      "Your perfect pack for everyday use and walks in the forest. Stash your laptop (up to 15 inches) in the padded sleeve, your everyday",
    category: "men's clothing",
    image: "/product-image/Front Pic.png",
    rating: { rate: 3.9, count: 120 },
    tags: ["travel", "work", "padded", "laptop"],
    isAvailable: true,
    favorite: true,
  },
  {
    id: 2,
    title: "Everyday Canvas Tote",
    price: 24.75,
    description:
      "Sturdy canvas bag with reinforced handles and a roomy interior for daily essentials.",
    category: "accessories",
    image: "/product-image/Rectangle 29438-4.png",
    rating: { rate: 3.8, count: 57 },
    tags: ["canvas", "tote", "sturdy", "everyday"],
    isAvailable: false,
    favorite: false,
  },
  {
    id: 3,
    title: "Ceramic Pour-Over Set",
    price: 32.0,
    description:
      "Two-cup pour-over kit with reusable filter and heat-safe ceramic dripper.",
    category: "home",
    image: "/product-image/Rectangle 29438-5.png",
    rating: { rate: 4.6, count: 93 },
    tags: ["ceramic", "coffee", "reusable", "eco-friendly"],
    isAvailable: true,
    favorite: false,
  },
  {
    id: 4,
    title: "Minimalist Leather Wallet",
    price: 18.99,
    description:
      "Slim profile wallet with RFID lining and room for eight cards plus folded cash.",
    category: "accessories",
    image: "/product-image/Rectangle 29438-3.png",
    rating: { rate: 4.1, count: 210 },
    tags: ["leather", "rfid", "slim", "minimalist"],
    isAvailable: true,
    favorite: true,
  },
  {
    id: 5,
    title: "Classic Cotton Crewneck Tee",
    price: 22.5,
    description:
      "Soft, breathable cotton with a durable collar. Perfect for layering or everyday wear.",
    category: "men's clothing",
    image: "/product-image/Rectangle 29438-1.png",
    rating: { rate: 4.2, count: 86 },
    tags: ["cotton", "casual", "breathable"],
    isAvailable: true,
    favorite: false,
  },
  {
    id: 6,
    title: "Minimal Desk Lamp",
    price: 44.0,
    description:
      "LED lamp with adjustable arm, warm glow, and touch-sensitive dimmer.",
    category: "home",
    image: "/product-image/Rectangle 29438-13.png",
    rating: { rate: 4.1, count: 27 },
    tags: ["led", "lamp", "desk", "minimalist"],
    isAvailable: true,
    favorite: false,
  },
  {
    id: 7,
    title: "Trail-Ready Cap",
    price: 16.5,
    description:
      "Lightweight cap with moisture-wicking band and adjustable back strap.",
    category: "outdoors",
    image: "/product-image/Rectangle 29438-11.png",
    rating: { rate: 4.2, count: 52 },
    tags: ["outdoor", "lightweight", "sports", "breathable"],
    isAvailable: true,
    favorite: false,
  },
  {
    id: 8,
    title: "Lightweight Travel Jacket",
    price: 64.0,
    description:
      "Wind-resistant outer shell with hidden pockets and a relaxed fit for daily commuting.",
    category: "men's clothing",
    image: "/product-image/Rectangle 29438-2.png",
    rating: { rate: 4.5, count: 41 },
    tags: ["travel", "wind-resistant", "jacket", "work"],
    isAvailable: true,
    favorite: false,
  },
  
  {
    id: 9,
    title: "Linen Blend Pillow Covers (2-Pack)",
    price: 19.5,
    description:
      "Neutral-toned pillow covers with hidden zippers and a soft linen blend texture.",
    category: "home",
    image: "/product-image/Rectangle 29438-6.png",
    rating: { rate: 4.0, count: 38 },
    tags: ["linen", "soft", "neutral", "home-decor"],
    isAvailable: true,
    favorite: false,
  },
  {
    id: 10,
    title: "Desk Organizer Tray",
    price: 14.25,
    description:
      "Compact tray to keep stationery, keys, and small tech neatly in one place.",
    category: "home",
    image: "/product-image/Rectangle 29438-7.png",
    rating: { rate: 3.7, count: 64 },
    tags: ["organizer", "desk", "compact", "work"],
    isAvailable: true,
    favorite: false,
  },
  {
    id: 11,
    title: "Wireless Earbuds Case",
    price: 9.99,
    description:
      "Soft-touch protective case with a snap-fit lid and detachable key ring.",
    category: "electronics",
    image: "/product-image/Rectangle 29438-8.png",
    rating: { rate: 4.3, count: 114 },
    tags: ["protective", "wireless", "tech", "portable"],
    isAvailable: true,
    favorite: false,
  },
  {
    id: 12,
    title: "Compact Bluetooth Speaker",
    price: 39.0,
    description:
      "Portable speaker with 10-hour battery life and balanced sound for small rooms.",
    category: "electronics",
    image: "/product-image/Rectangle 29438-9.png",
    rating: { rate: 4.4, count: 78 },
    tags: ["bluetooth", "portable", "audio", "tech"],
    isAvailable: true,
    favorite: true,
  },
  {
    id: 13,
    title: "Stainless Steel Water Bottle",
    price: 21.0,
    description:
      "Insulated bottle that keeps drinks cold for 24 hours and hot for 8 hours.",
    category: "outdoors",
    image: "/product-image/Rectangle 29438-10.png",
    rating: { rate: 4.8, count: 142 },
    tags: ["stainless-steel", "insulated", "travel", "eco-friendly"],
    isAvailable: true,
    favorite: false,
  },
  {
    id: 14,
    title: "Everyday Journal",
    price: 12.75,
    description:
      "Hardcover notebook with dot grid pages and a lay-flat binding.",
    category: "stationery",
    image: "/product-image/Rectangle 29438-12.png",
    rating: { rate: 4.6, count: 31 },
    tags: ["journal", "stationery", "dot-grid", "work"],
    isAvailable: true,
    favorite: false,
  },
  {
    id: 15,
    title: "Everyday Running Socks (3-Pack)",
    price: 13.25,
    description:
      "Cushioned socks with arch support and breathable mesh panels.",
    category: "sports",
    image: "/product-image/Rectangle 29438-14.png",
    rating: { rate: 3.9, count: 49 },
    tags: ["cushioned", "sports", "breathable", "athletic"],
    isAvailable: true,
    favorite: false,
  },
  {
    id: 16,
    title: "Structured Baseball Cap",
    price: 18.0,
    description:
      "Six-panel cap with a pre-curved brim and adjustable buckle closure.",
    category: "accessories",
    image: "/product-image/Rectangle 29438-15.png",
    rating: { rate: 4.0, count: 33 },
    tags: ["cap", "structured", "casual", "adjustable"],
    isAvailable: true,
    favorite: false,
  },
  {
    id: 17,
    title: "Soft Knit Throw Blanket",
    price: 28.5,
    description:
      "Cozy knit throw with a subtle texture and medium-weight warmth.",
    category: "home",
    image: "/product-image/Rectangle 29438.png",
    rating: { rate: 4.7, count: 65 },
    tags: ["knit", "cozy", "blanket", "home-decor"],
    isAvailable: true,
    favorite: false,
  },
];
